# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1228, 704)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(640, 420))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1208, 643))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tour6BTM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour6BTM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour6BTM.setFont(font)
        self.tour6BTM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour6BTM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour6BTM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour6BTM.setObjectName("tour6BTM")
        self.tour6BTM.horizontalHeader().setDefaultSectionSize(100)
        self.tour6BTM.horizontalHeader().setMinimumSectionSize(15)
        self.tour6BTM.horizontalHeader().setStretchLastSection(True)
        self.tour6BTM.verticalHeader().setVisible(False)
        self.tour6BTM.verticalHeader().setCascadingSectionResizes(True)
        self.tour6BTM.verticalHeader().setDefaultSectionSize(20)
        self.tour6BTM.verticalHeader().setHighlightSections(True)
        self.tour6BTM.verticalHeader().setMinimumSectionSize(18)
        self.tour6BTM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour6BTM, 3, 8, 1, 1)
        self.tour1ATV = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour1ATV.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour1ATV.setFont(font)
        self.tour1ATV.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour1ATV.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour1ATV.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour1ATV.setObjectName("tour1ATV")
        self.tour1ATV.horizontalHeader().setDefaultSectionSize(100)
        self.tour1ATV.horizontalHeader().setMinimumSectionSize(15)
        self.tour1ATV.horizontalHeader().setStretchLastSection(True)
        self.tour1ATV.verticalHeader().setVisible(False)
        self.tour1ATV.verticalHeader().setCascadingSectionResizes(True)
        self.tour1ATV.verticalHeader().setDefaultSectionSize(20)
        self.tour1ATV.verticalHeader().setHighlightSections(True)
        self.tour1ATV.verticalHeader().setMinimumSectionSize(18)
        self.tour1ATV.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour1ATV, 1, 1, 3, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 9, 1, 1)
        self.tour7BTM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour7BTM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour7BTM.setFont(font)
        self.tour7BTM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour7BTM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour7BTM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour7BTM.setObjectName("tour7BTM")
        self.tour7BTM.horizontalHeader().setDefaultSectionSize(100)
        self.tour7BTM.horizontalHeader().setMinimumSectionSize(15)
        self.tour7BTM.horizontalHeader().setStretchLastSection(True)
        self.tour7BTM.verticalHeader().setVisible(False)
        self.tour7BTM.verticalHeader().setCascadingSectionResizes(True)
        self.tour7BTM.verticalHeader().setDefaultSectionSize(20)
        self.tour7BTM.verticalHeader().setHighlightSections(True)
        self.tour7BTM.verticalHeader().setMinimumSectionSize(18)
        self.tour7BTM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour7BTM, 3, 9, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(390, 0))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableView = QtWidgets.QTableView(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.tableView.setFont(font)
        self.tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableView.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableView.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setDefaultSectionSize(58)
        self.tableView.horizontalHeader().setHighlightSections(True)
        self.tableView.horizontalHeader().setSortIndicatorShown(True)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(True)
        self.tableView.verticalHeader().setDefaultSectionSize(20)
        self.tableView.verticalHeader().setHighlightSections(False)
        self.tableView.verticalHeader().setMinimumSectionSize(20)
        self.tableView.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.addNewPlayerButton = QtWidgets.QPushButton(self.groupBox)
        self.addNewPlayerButton.setObjectName("addNewPlayerButton")
        self.gridLayout_4.addWidget(self.addNewPlayerButton, 1, 0, 1, 1)
        self.deleteFromMainTM = QtWidgets.QPushButton(self.groupBox)
        self.deleteFromMainTM.setObjectName("deleteFromMainTM")
        self.gridLayout_4.addWidget(self.deleteFromMainTM, 1, 1, 1, 1)
        self.firstTourAddingCB = QtWidgets.QComboBox(self.groupBox)
        self.firstTourAddingCB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.firstTourAddingCB.setAutoFillBackground(False)
        self.firstTourAddingCB.setEditable(False)
        self.firstTourAddingCB.setObjectName("firstTourAddingCB")
        self.firstTourAddingCB.addItem("")
        self.firstTourAddingCB.addItem("")
        self.gridLayout_4.addWidget(self.firstTourAddingCB, 2, 0, 1, 1)
        self.firstTourBtn = QtWidgets.QPushButton(self.groupBox)
        self.firstTourBtn.setObjectName("firstTourBtn")
        self.gridLayout_4.addWidget(self.firstTourBtn, 1, 3, 1, 1)
        self.addPlayerFromMainTVBtn = QtWidgets.QPushButton(self.groupBox)
        self.addPlayerFromMainTVBtn.setObjectName("addPlayerFromMainTVBtn")
        self.gridLayout_4.addWidget(self.addPlayerFromMainTVBtn, 2, 3, 1, 1)
        self.deleteFromFirstTourTV = QtWidgets.QPushButton(self.groupBox)
        self.deleteFromFirstTourTV.setObjectName("deleteFromFirstTourTV")
        self.gridLayout_4.addWidget(self.deleteFromFirstTourTV, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 4, 1)
        self.tour3BTM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour3BTM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour3BTM.setFont(font)
        self.tour3BTM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour3BTM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour3BTM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour3BTM.setObjectName("tour3BTM")
        self.tour3BTM.horizontalHeader().setDefaultSectionSize(100)
        self.tour3BTM.horizontalHeader().setMinimumSectionSize(15)
        self.tour3BTM.horizontalHeader().setStretchLastSection(True)
        self.tour3BTM.verticalHeader().setVisible(False)
        self.tour3BTM.verticalHeader().setCascadingSectionResizes(True)
        self.tour3BTM.verticalHeader().setDefaultSectionSize(20)
        self.tour3BTM.verticalHeader().setHighlightSections(True)
        self.tour3BTM.verticalHeader().setMinimumSectionSize(18)
        self.tour3BTM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour3BTM, 3, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 6, 1, 1)
        self.tour2ATM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour2ATM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour2ATM.setFont(font)
        self.tour2ATM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour2ATM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour2ATM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour2ATM.setObjectName("tour2ATM")
        self.tour2ATM.horizontalHeader().setDefaultSectionSize(100)
        self.tour2ATM.horizontalHeader().setMinimumSectionSize(15)
        self.tour2ATM.horizontalHeader().setStretchLastSection(True)
        self.tour2ATM.verticalHeader().setVisible(False)
        self.tour2ATM.verticalHeader().setCascadingSectionResizes(True)
        self.tour2ATM.verticalHeader().setDefaultSectionSize(20)
        self.tour2ATM.verticalHeader().setHighlightSections(True)
        self.tour2ATM.verticalHeader().setMinimumSectionSize(18)
        self.tour2ATM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour2ATM, 1, 2, 1, 1)
        self.tour4ATM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour4ATM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour4ATM.setFont(font)
        self.tour4ATM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour4ATM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour4ATM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour4ATM.setObjectName("tour4ATM")
        self.tour4ATM.horizontalHeader().setDefaultSectionSize(100)
        self.tour4ATM.horizontalHeader().setMinimumSectionSize(15)
        self.tour4ATM.horizontalHeader().setStretchLastSection(True)
        self.tour4ATM.verticalHeader().setVisible(False)
        self.tour4ATM.verticalHeader().setCascadingSectionResizes(True)
        self.tour4ATM.verticalHeader().setDefaultSectionSize(20)
        self.tour4ATM.verticalHeader().setHighlightSections(True)
        self.tour4ATM.verticalHeader().setMinimumSectionSize(18)
        self.tour4ATM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour4ATM, 1, 6, 1, 1)
        self.tour2BTM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour2BTM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour2BTM.setFont(font)
        self.tour2BTM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour2BTM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour2BTM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour2BTM.setObjectName("tour2BTM")
        self.tour2BTM.horizontalHeader().setDefaultSectionSize(100)
        self.tour2BTM.horizontalHeader().setMinimumSectionSize(15)
        self.tour2BTM.horizontalHeader().setStretchLastSection(True)
        self.tour2BTM.verticalHeader().setVisible(False)
        self.tour2BTM.verticalHeader().setCascadingSectionResizes(True)
        self.tour2BTM.verticalHeader().setDefaultSectionSize(20)
        self.tour2BTM.verticalHeader().setHighlightSections(True)
        self.tour2BTM.verticalHeader().setMinimumSectionSize(18)
        self.tour2BTM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour2BTM, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 2, 1, 1)
        self.tour3ATM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour3ATM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour3ATM.setFont(font)
        self.tour3ATM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour3ATM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour3ATM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour3ATM.setObjectName("tour3ATM")
        self.tour3ATM.horizontalHeader().setDefaultSectionSize(100)
        self.tour3ATM.horizontalHeader().setMinimumSectionSize(15)
        self.tour3ATM.horizontalHeader().setStretchLastSection(True)
        self.tour3ATM.verticalHeader().setVisible(False)
        self.tour3ATM.verticalHeader().setCascadingSectionResizes(True)
        self.tour3ATM.verticalHeader().setDefaultSectionSize(20)
        self.tour3ATM.verticalHeader().setHighlightSections(True)
        self.tour3ATM.verticalHeader().setMinimumSectionSize(18)
        self.tour3ATM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour3ATM, 1, 4, 1, 1)
        self.tour4BTM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour4BTM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour4BTM.setFont(font)
        self.tour4BTM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour4BTM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour4BTM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour4BTM.setObjectName("tour4BTM")
        self.tour4BTM.horizontalHeader().setDefaultSectionSize(100)
        self.tour4BTM.horizontalHeader().setMinimumSectionSize(15)
        self.tour4BTM.horizontalHeader().setStretchLastSection(True)
        self.tour4BTM.verticalHeader().setVisible(False)
        self.tour4BTM.verticalHeader().setCascadingSectionResizes(True)
        self.tour4BTM.verticalHeader().setDefaultSectionSize(20)
        self.tour4BTM.verticalHeader().setHighlightSections(True)
        self.tour4BTM.verticalHeader().setMinimumSectionSize(18)
        self.tour4BTM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour4BTM, 3, 6, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 8, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 4, 1, 1)
        self.tour6ATM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour6ATM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour6ATM.setFont(font)
        self.tour6ATM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour6ATM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour6ATM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour6ATM.setObjectName("tour6ATM")
        self.tour6ATM.horizontalHeader().setDefaultSectionSize(100)
        self.tour6ATM.horizontalHeader().setMinimumSectionSize(15)
        self.tour6ATM.horizontalHeader().setStretchLastSection(True)
        self.tour6ATM.verticalHeader().setVisible(False)
        self.tour6ATM.verticalHeader().setCascadingSectionResizes(True)
        self.tour6ATM.verticalHeader().setDefaultSectionSize(20)
        self.tour6ATM.verticalHeader().setHighlightSections(True)
        self.tour6ATM.verticalHeader().setMinimumSectionSize(18)
        self.tour6ATM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour6ATM, 1, 8, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 8, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 6, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 7, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 7, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 4, 1, 1)
        self.tour5ATM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour5ATM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour5ATM.setFont(font)
        self.tour5ATM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour5ATM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour5ATM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour5ATM.setObjectName("tour5ATM")
        self.tour5ATM.horizontalHeader().setDefaultSectionSize(100)
        self.tour5ATM.horizontalHeader().setMinimumSectionSize(15)
        self.tour5ATM.horizontalHeader().setStretchLastSection(True)
        self.tour5ATM.verticalHeader().setVisible(False)
        self.tour5ATM.verticalHeader().setCascadingSectionResizes(True)
        self.tour5ATM.verticalHeader().setDefaultSectionSize(20)
        self.tour5ATM.verticalHeader().setHighlightSections(True)
        self.tour5ATM.verticalHeader().setMinimumSectionSize(18)
        self.tour5ATM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour5ATM, 1, 7, 1, 1)
        self.tour5BTM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour5BTM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour5BTM.setFont(font)
        self.tour5BTM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour5BTM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour5BTM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour5BTM.setObjectName("tour5BTM")
        self.tour5BTM.horizontalHeader().setDefaultSectionSize(100)
        self.tour5BTM.horizontalHeader().setMinimumSectionSize(15)
        self.tour5BTM.horizontalHeader().setStretchLastSection(True)
        self.tour5BTM.verticalHeader().setVisible(False)
        self.tour5BTM.verticalHeader().setCascadingSectionResizes(True)
        self.tour5BTM.verticalHeader().setDefaultSectionSize(20)
        self.tour5BTM.verticalHeader().setHighlightSections(True)
        self.tour5BTM.verticalHeader().setMinimumSectionSize(18)
        self.tour5BTM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour5BTM, 3, 7, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 9, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 10, 1, 1)
        self.tour7ATM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour7ATM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour7ATM.setFont(font)
        self.tour7ATM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour7ATM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour7ATM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour7ATM.setObjectName("tour7ATM")
        self.tour7ATM.horizontalHeader().setDefaultSectionSize(100)
        self.tour7ATM.horizontalHeader().setMinimumSectionSize(15)
        self.tour7ATM.horizontalHeader().setStretchLastSection(True)
        self.tour7ATM.verticalHeader().setVisible(False)
        self.tour7ATM.verticalHeader().setCascadingSectionResizes(True)
        self.tour7ATM.verticalHeader().setDefaultSectionSize(20)
        self.tour7ATM.verticalHeader().setHighlightSections(True)
        self.tour7ATM.verticalHeader().setMinimumSectionSize(18)
        self.tour7ATM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour7ATM, 1, 9, 1, 1)
        self.tour8ATM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour8ATM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour8ATM.setFont(font)
        self.tour8ATM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour8ATM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour8ATM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour8ATM.setObjectName("tour8ATM")
        self.tour8ATM.horizontalHeader().setDefaultSectionSize(100)
        self.tour8ATM.horizontalHeader().setMinimumSectionSize(15)
        self.tour8ATM.horizontalHeader().setStretchLastSection(True)
        self.tour8ATM.verticalHeader().setVisible(False)
        self.tour8ATM.verticalHeader().setCascadingSectionResizes(True)
        self.tour8ATM.verticalHeader().setDefaultSectionSize(20)
        self.tour8ATM.verticalHeader().setHighlightSections(True)
        self.tour8ATM.verticalHeader().setMinimumSectionSize(18)
        self.tour8ATM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour8ATM, 1, 10, 1, 1)
        self.tour8BTM = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.tour8BTM.setMinimumSize(QtCore.QSize(90, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tour8BTM.setFont(font)
        self.tour8BTM.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tour8BTM.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour8BTM.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tour8BTM.setObjectName("tour8BTM")
        self.tour8BTM.horizontalHeader().setDefaultSectionSize(100)
        self.tour8BTM.horizontalHeader().setMinimumSectionSize(15)
        self.tour8BTM.horizontalHeader().setStretchLastSection(True)
        self.tour8BTM.verticalHeader().setVisible(False)
        self.tour8BTM.verticalHeader().setCascadingSectionResizes(True)
        self.tour8BTM.verticalHeader().setDefaultSectionSize(20)
        self.tour8BTM.verticalHeader().setHighlightSections(True)
        self.tour8BTM.verticalHeader().setMinimumSectionSize(18)
        self.tour8BTM.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tour8BTM, 3, 10, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 2, 10, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1228, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openAction = QtWidgets.QAction(MainWindow)
        self.openAction.setObjectName("openAction")
        self.saveAsAction = QtWidgets.QAction(MainWindow)
        self.saveAsAction.setObjectName("saveAsAction")
        self.saveMainTM = QtWidgets.QAction(MainWindow)
        self.saveMainTM.setObjectName("saveMainTM")
        self.saveReport = QtWidgets.QAction(MainWindow)
        self.saveReport.setObjectName("saveReport")
        self.aboutAction = QtWidgets.QAction(MainWindow)
        self.aboutAction.setObjectName("aboutAction")
        self.menu.addAction(self.openAction)
        self.menu.addAction(self.saveAsAction)
        self.menu.addAction(self.saveMainTM)
        self.menu.addAction(self.saveReport)
        self.menu_2.addAction(self.aboutAction)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_19.setText(_translate("MainWindow", "Тур 7Б"))
        self.groupBox.setTitle(_translate("MainWindow", "Таблица участников"))
        self.addNewPlayerButton.setText(_translate("MainWindow", "Добавить"))
        self.deleteFromMainTM.setText(_translate("MainWindow", "Удалить с главной"))
        self.firstTourAddingCB.setCurrentText(_translate("MainWindow", "Авто ввод"))
        self.firstTourAddingCB.setItemText(0, _translate("MainWindow", "Авто ввод"))
        self.firstTourAddingCB.setItemText(1, _translate("MainWindow", "Ручной ввод"))
        self.firstTourBtn.setText(_translate("MainWindow", "Начать турнир"))
        self.addPlayerFromMainTVBtn.setText(_translate("MainWindow", "Добавить в 1 тур"))
        self.deleteFromFirstTourTV.setText(_translate("MainWindow", "Удалить с 1 тура"))
        self.label_13.setText(_translate("MainWindow", "Тур 4А"))
        self.label_9.setText(_translate("MainWindow", "Тур 2Б"))
        self.label_17.setText(_translate("MainWindow", "Тур 6Б"))
        self.label_10.setText(_translate("MainWindow", "Тур 3Б"))
        self.label_16.setText(_translate("MainWindow", "Полуфинал"))
        self.label_11.setText(_translate("MainWindow", "Тур 4Б"))
        self.label_7.setText(_translate("MainWindow", "Тур 1"))
        self.label_8.setText(_translate("MainWindow", "Тур 2А"))
        self.label_15.setText(_translate("MainWindow", "Тур 5А"))
        self.label_14.setText(_translate("MainWindow", "Тур 5Б"))
        self.label_12.setText(_translate("MainWindow", "Тур 3А"))
        self.label_18.setText(_translate("MainWindow", "Финал"))
        self.label_20.setText(_translate("MainWindow", "Суперфинал"))
        self.label_21.setText(_translate("MainWindow", "Тур 8Б"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Помощь"))
        self.openAction.setText(_translate("MainWindow", "Открыть"))
        self.saveAsAction.setText(_translate("MainWindow", "Сохранить как"))
        self.saveMainTM.setText(_translate("MainWindow", "Сохранить главную таблицу"))
        self.saveReport.setText(_translate("MainWindow", "Сохранить все таблицы"))
        self.aboutAction.setText(_translate("MainWindow", "О программе"))

